FROM debian:jessie

# Install system dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y python-pip python-dev && \
    apt-get install -y curl bison && \
    apt-get install -y  git && \
    rm -rf /var/lib/apt/lists/*

# Workaround gvm non-portability by replacing sh
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Creating test account
RUN adduser --quiet testing

# Copy contrib folder
ENV BUILD_DIR /home/testing/build
COPY ./gvm $BUILD_DIR/gvm
RUN chown -R testing $BUILD_DIR
RUN mkdir -p /src && chown -R testing /src

# && mkdir -p /go/pkg
# Switch to user testing
# USER testing

# Setup dev tools
RUN pip install --user codecov

# Setup gvm base
RUN $BUILD_DIR/gvm/binscripts/gvm-installer && \
    source ~/.gvm/scripts/gvm && \
    gvm install go1.4.3 --prefer-binary && \
    gvm install go1.5.3 --prefer-binary && \
    gvm install go1.6rc2 --prefer-binary && \
    gvm alias create 1.4 go1.4.3 && \
    gvm alias create 1.5 go1.5.3 && \
    gvm alias create 1.6 go1.6rc2 && \
    gvm alias create old 1.4 && \
    gvm alias create stable 1.5 && \
    gvm alias create future 1.6 && \
    gvm use 1.4 && \
    go get github.com/axw/gocov/gocov github.com/golang/lint/golint && \
    gvm use 1.5 && \
    go get github.com/axw/gocov/gocov github.com/golang/lint/golint && \
    gvm use 1.6 && \
    go get github.com/axw/gocov/gocov github.com/golang/lint/golint

# Install magic
COPY ./my /usr/local/bin/

ENV MY_REPO dmp42/scape-go
ENV MY_BUILDTAGS ""

VOLUME /src
WORKDIR /src

ENTRYPOINT ["my"]
